name: Deployment

on:
  workflow_call:
    inputs:
      message:
        description: 'Message for the deployment'
        required: true
        type: string
    secrets:
      gh-token:
        description: 'GitHub token to use for authentication'
        required: true

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.gh-token }}

      - name: Deploy to Server
        run: echo "Deploying to server..."

      - name: Post Deployment Message
        run: echo "${{ inputs.message }}"